version: '3.8'
services:
  # Serviço da Aplicação (Laravel/PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html      # CORRIGIDO: Mapeia o código
      - /var/www/html/vendor # CORRIGIDO: Protege a pasta vendor da imagem
    networks:
      - laravel-net
    depends_on:
      mysql_db:
        condition: service_healthy
    command: sh -c "php artisan migrate --force && php-fpm"

  # Serviço do Servidor Web (Nginx)
  nginx:
    image: nginx:1.19-alpine
    container_name: crud_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net

  # Serviço do Banco de Dados (MySQL)
  mysql_db:
    image: mysql:8.0
    container_name: crud_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-user}
    volumes:
      - mysql_data:/var/lib/mysql # CORRIGIDO: Usando volume nomeado
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - laravel-net
    healthcheck:
       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
       timeout: 20s
       retries: 10
       start_period: 10s

  # Serviço para Desenvolvimento (Vite)
  vite:
    image: node:18-alpine
    container_name: crud_vite
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html           # Mapeia o código
      - /var/www/html/node_modules # OTIMIZADO: Protege a pasta node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel-net
    profiles:
      - dev

networks:
  laravel-net:
    driver: bridge

# CORRIGIDO: Declaração do volume nomeado para o MySQL
volumes:
  mysql_data:
    driver: local